# Generated by Django 4.0 on 2022-05-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_customer_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Akan dihubungi admin', 'Akan dihubungi admin'), ('Proses', 'Proses'), ('Selesai', 'Selesai')], default='Akan dihubungi admin', max_length=200),
        ),
    ]
