# Generated by Django 4.0 on 2022-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_customer_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='order/gambar')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
