# Generated by Django 4.0 on 2022-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_gambar_alter_customer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambar',
            name='gambar',
            field=models.ImageField(upload_to='gambar'),
        ),
    ]
